-- Initialize the database.
-- Drop any existing data and create empty tables.

DROP TABLE IF EXISTS calendar;
DROP TABLE IF EXISTS listings;
DROP TABLE IF EXISTS reviews;


CREATE TABLE calendar(
  "listing_id" TEXT,
  "date" TEXT,
  "available" TEXT,
  "price" TEXT
);

CREATE TABLE listings(
  "id" TEXT,
  "listing_url" TEXT,
  "scrape_id" TEXT,
  "last_scraped" TEXT,
  "name" TEXT,
  "summary" TEXT,
  "space" TEXT,
  "description" TEXT,
  "experiences_offered" TEXT,
  "neighborhood_overview" TEXT,
  "notes" TEXT,
  "transit" TEXT,
  "access" TEXT,
  "interaction" TEXT,
  "house_rules" TEXT,
  "thumbnail_url" TEXT,
  "medium_url" TEXT,
  "picture_url" TEXT,
  "xl_picture_url" TEXT,
  "host_id" TEXT,
  "host_url" TEXT,
  "host_name" TEXT,
  "host_since" TEXT,
  "host_location" TEXT,
  "host_about" TEXT,
  "host_response_time" TEXT,
  "host_response_rate" TEXT,
  "host_acceptance_rate" TEXT,
  "host_is_superhost" TEXT,
  "host_thumbnail_url" TEXT,
  "host_picture_url" TEXT,
  "host_neighbourhood" TEXT,
  "host_listings_count" TEXT,
  "host_total_listings_count" TEXT,
  "host_verifications" TEXT,
  "host_has_profile_pic" TEXT,
  "host_identity_verified" TEXT,
  "street" TEXT,
  "neighbourhood" TEXT,
  "neighbourhood_cleansed" TEXT,
  "neighbourhood_group_cleansed" TEXT,
  "city" TEXT,
  "state" TEXT,
  "zipcode" TEXT,
  "market" TEXT,
  "smart_location" TEXT,
  "country_code" TEXT,
  "country" TEXT,
  "latitude" TEXT,
  "longitude" TEXT,
  "is_location_exact" TEXT,
  "property_type" TEXT,
  "room_type" TEXT,
  "accommodates" TEXT,
  "bathrooms" TEXT,
  "bedrooms" TEXT,
  "beds" TEXT,
  "bed_type" TEXT,
  "amenities" TEXT,
  "square_feet" TEXT,
  "price" TEXT,
  "weekly_price" TEXT,
  "monthly_price" TEXT,
  "security_deposit" TEXT,
  "cleaning_fee" TEXT,
  "guests_included" TEXT,
  "extra_people" TEXT,
  "minimum_nights" TEXT,
  "maximum_nights" TEXT,
  "calendar_updated" TEXT,
  "has_availability" TEXT,
  "availability_30" TEXT,
  "availability_60" TEXT,
  "availability_90" TEXT,
  "availability_365" TEXT,
  "calendar_last_scraped" TEXT,
  "number_of_reviews" TEXT,
  "first_review" TEXT,
  "last_review" TEXT,
  "review_scores_rating" TEXT,
  "review_scores_accuracy" TEXT,
  "review_scores_cleanliness" TEXT,
  "review_scores_checkin" TEXT,
  "review_scores_communication" TEXT,
  "review_scores_location" TEXT,
  "review_scores_value" TEXT,
  "requires_license" TEXT,
  "license" TEXT,
  "jurisdiction_names" TEXT,
  "instant_bookable" TEXT,
  "is_business_travel_ready" TEXT,
  "cancellation_policy" TEXT,
  "require_guest_profile_picture" TEXT,
  "require_guest_phone_verification" TEXT,
  "calculated_host_listings_count" TEXT,
  "reviews_per_month" TEXT
);

CREATE TABLE reviews(
  "listing_id" TEXT,
  "id" TEXT,
  "date" TEXT,
  "reviewer_id" TEXT,
  "reviewer_name" TEXT,
  "comments" TEXT
);